[tool.poetry]
name = "python-dlt"
version = "0.0.1"
description = "DLT is an open-source python-native scalable data loading framework that does not require any devops efforts to run."
authors = ["Marcin Rudolf <rudolfix@rudolfix.org>"]
license = "MIT"
packages = [
    { include = "dlt" },
]

[tool.poetry.dependencies]
python = "^3.8,<3.11"
# autopoiesis = {path = "../rasa_data_ingestion"}


[tool.poetry.dev-dependencies]
pytest = "6.2.4"
mypy = "0.931"
flake8 = "3.9.2"
bandit = "1.7.0"
flake8-bugbear = "21.4.3"
pytest-pythonpath = "0.7.3"
pytest-order = "^1.0.0"
pytest-cases = "^3.6.9"
types-PyYAML = "^6.0.7"
types-cachetools = "^4.2.9"
types-protobuf = "^3.19.8"
types-simplejson = "^3.17.0"
types-requests = "^2.25.6"
types-python-dateutil = "^2.8.15"

[build-system]
requires = ["poetry-core>=1.0.8"]
build-backend = "poetry.core.masonry.api"
