
name: test common

on:
  pull_request:
    branches:
      - master


jobs:

  run_lint:
    name: Tests common dlt code
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}

    steps:

      - name: Check out
        uses: actions/checkout@master

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.9.x"

      - name: Install Poetry
        # https://github.com/snok/install-poetry#running-on-windows
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Get pip cache dir
        id: pip-cache
        run: |
          echo "::set-output name=dir::$(poetry run pip cache dir)"
          echo "$(poetry run pip cache dir)"

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v2
        with:
          # For some reason, caching your venv does not seem to work as expected on Windows runners. You can see an example of what happens here, where a workflow stalls and runs for over 3 hours before it was manually cancelled.
          path: ${{ steps.pip-cache.outputs.dir }}
          key: pip-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --no-root

      - name: Install self
        run: poetry install --no-interaction

      - run: |
          LOG_LEVEL=ERROR poetry run pytest tests --ignore=tests/loaders --ignore=tests/dbt_runner
        if: runner.os != 'Windows'
        name: Run tests Linux/MAC
      - run: |
          poetry run pytest tests --ignore=tests/loaders --ignore=tests/dbt_runner -m "not forked"
        if: runner.os == 'Windows'
        name: Run tests Windows
        shell: cmd
