# here is a file with the secrets for all the example pipelines in `examples` folder

# google sheets example
[sources.google_spreadsheet]
project_id="..."
client_email="..."
private_key="..."


# all postgres destinations for all examples
destination.postgres.credentials = "postgres://loader:loader@localhost:5432/dlt_data"
# all redshift destinations for all examples
destination.redshift.credentials = "postgres://loader:<password>@<host>.redshift.amazonaws.com:5439/<database name>"
# all the bigquery destinations
[destination.bigquery.credentials]
project_id="..."
client_email="..."
private_key="..."